### ISSUE TITLE
Add Storage.create() method which takes a restartable input stream

### ISSUE THREAD

**Issue by frankyn** [googleapis/java-storage#201]
Filing feature request that was raised in: 
https://github.com/googleapis/google-cloud-java/issues/2620

So it doesn't get lost.

**Comment by dmitry-fa** [comment]
Will it be enough to implement upload based on WriterChannel?

**Comment by dmitry-fa** [comment]
Hi @frankyn,

Is this functionality really needed?
Justification for that request (https://github.com/googleapis/google-cloud-java/issues/2620) sounds like: ` so that it is easier for users to create blobs without loading the entire content into memory.`
But `Storage.create(IntputStream)` doesn't load the entire content into memory. I successfully uploaded 1.5Gb on the JVM with the heap of 50M (-Xmx50m).  Upload is implemented in:

```
com.google.api.client.http.AbstractInputStreamContent {
    public void writeTo(OutputStream out) throws IOException {
        IOUtils.copy(this.getInputStream(), out, this.closeInputStream);
        out.flush();
    }
}
```
IOUtils.copy() uses buffer of 4096 bytes to read from and write to the given streams, so no problem with memory.

As you probably remember, #179 will introduce a number of upload() methods which read the content portion by portion and applies resumable approach. 

Even if upload with a restartable input stream is still needed for some reason, it could be implemented without introducing a new class representing `a restartable input stream` (as it implemented in https://github.com/googleapis/google-cloud-java/pull/2682), no need to expose internal details to public. Upload details can be reflected in the method name:

```
  public Blob createBlobUsingRestorableInputStream(blobInfo, inputStream, options) {
     RestorableInputStream  restorable = new RestorableInputStream (inputStream);
   ...
  }
```
I personally do not see any benefits from adding such method. Do you?
