### ISSUE TITLE
Download an object's last n bytes

### ISSUE THREAD

**Issue by frcroth** [googleapis/java-storage#2030]
Downloading objects via byte ranges is supported (https://cloud.google.com/storage/docs/samples/storage-download-byte-range). However, seeking the channel does not work when I need to download the last n bytes of an object.
This is supported in the HTTP Range header with a negative value, describing the suffix length. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range).

Ideally I would like to give another parameter to download, an option object describing that or a new RangeReader.

Is this feature already implemented?

**Describe alternatives you've considered**
A possible workaround could be to first get the size and use this to get the start position. This is not ideal, as it would require two HTTP requests.

**Additional context**
In Go this was already discussed and implemented (https://github.com/googleapis/google-cloud-go/issues/1540). However, I am not sure, if the seekable channel would support something like this.

**Comment by BenWhitehead** [comment]
This was implemented[1] back in March, and is available from version 2.20.0 onward.

We have a test[3] which verifies this behavior. In order to read of a negative offset, a limit must not be set. If a limit is set, the negative offset will be ignored.

[1] https://github.com/googleapis/java-storage/pull/1916
[2] https://github.com/googleapis/java-storage/releases/tag/v2.20.0
[3] https://github.com/googleapis/java-storage/blame/260b6e52b379b80a1e31a32231a708556a62a75e/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITBlobReadChannelTest.java#L462-L481

**Comment by frcroth** [comment]
Thank you very much!
