### ISSUE TITLE
Blob.update() misses BlobInfo argument

### ISSUE THREAD

**Issue by dmitry-fa** [googleapis/java-storage#234]
The Blob class declares method: `public Blob update(BlobTargetOption... options)`
This method is useless, it doesn't have the necessary BlobInfo parameter.
Documentation to this method mentions Storage.update(), not Blob.update().

This method should be declared as Deprecated (and deleted as soon possible)

A new  method with BlobInfo parameter should be added.

**Comment by frankyn** [comment]
I don't agree we should deprecate this method. Closing this issue for now as I'd prefer organizing a deprecation because users may depend on this method.

An alternative would be to update documentation on how to use this method instead.

Here's an example of how to update metadata for Blob. A similar flow works with Bucket.update() as well.
```java
    Bucket remoteBucket = storage.get("bucket-name");
    Blob remoteBlob = remoteBucket.get("test");
    remoteBlob.toBuilder().setContentType("text/plain").build().update();
```

**Comment by dmitry-fa** [comment]
Hi @frankyn, thanks for that example. Yes, I agree, it's not necessary to deprecate this method.
I submitted https://github.com/googleapis/java-storage/issues/252 to fix the spec.
