### ISSUE TITLE
 Issue with GCS matchGlob method

### ISSUE THREAD

**Issue by utpalsharma** [googleapis/java-storage#2484]
Dear Google Cloud Support,  

We are currently experiencing an issue with the matchGlob method in Google Cloud Storage. Our GCS bucket has a structure as follows:

```java
v2-abc/code/code-123
v2-abc/policy/code-123
```
Our goal is to search for objects by user key, for example "code-123". To achieve this, we are using the matchGlob method as shown below:

```java
storage.list("bucketName", Storage.BlobListOption.matchGlob("v2-abc/**/code-123"));
```
However, this method call consistently returns an empty result, which is not the expected behavior given that an object with the key "code-123" does exist in the bucket or we understood the api behavior wrongly.

We would appreciate your assistance in resolving this issue. Is there a different approach we should be taking to search for objects by key using a glob pattern, or could this be a potential issue with the matchGlob method?  

Thank you for your time and assistance.

**Comment by BenWhitehead** [comment]
Hi, Unfortunately I wasn't able to reproduce empty results. But I will include my repro attempt in the hopes that it might help you determine if you're missing anything.

### My bucket state
#### Objects
  1. `gs://my-bucket/a/b/1.txt`
  1. `gs://my-bucket/a/b/c/abc-123.txt`
  1. `gs://my-bucket/a/b/c/abc.txt`
  1. `gs://my-bucket/a/b/d/abd.txt`
  1. `gs://my-bucket/a/z/1.txt`
  1. `gs://my-bucket/a/z/c/azc-123.txt`
  1. `gs://my-bucket/a/z/c/azc.txt`
  1. `gs://my-bucket/a/z/d/azd.txt`

### My repro attempt code
```java
import com.google.api.gax.paging.Page;
import com.google.cloud.storage.Blob;
import com.google.cloud.storage.BlobId;
import com.google.cloud.storage.BlobInfo;
import com.google.cloud.storage.Storage;
import com.google.cloud.storage.Storage.BlobListOption;
import com.google.cloud.storage.StorageOptions;

public final class ListObjects {
  public static void main(String[] args) throws Exception {
    try (Storage s = StorageOptions.getDefaultInstance().getService()) {
      listGlob(s, "a/**/c");
      listGlob(s, "a/**/1.txt");
      listGlob(s, "a/**/c/*");
      listGlob(s, "a/**/c*");
      listGlob(s, "a/**/c**");
    }
  }
  private static void listGlob(Storage s, String glob) {
    System.out.printf("glob = %s%n", glob);
    Page<Blob> page = s.list("my-bucket", BlobListOption.matchGlob(glob));

    page.streamAll()
        .map(BlobInfo::getBlobId)
        .map(BlobId::toGsUtilUriWithGeneration)
        .forEach(uri -> System.out.printf("blob = %s%n", uri));
  }
}
```

### The output from running the repro 
```
glob = a/**/c
glob = a/**/1.txt
blob = gs://my-bucket/a/b/1.txt#1712257207265055
blob = gs://my-bucket/a/z/1.txt#1712257206773890
glob = a/**/c/*
blob = gs://my-bucket/a/b/c/abc-123.txt#1712257207431039
blob = gs://my-bucket/a/b/c/abc.txt#1712257207497081
blob = gs://my-bucket/a/z/c/azc-123.txt#1712257207116778
blob = gs://my-bucket/a/z/c/azc.txt#1712257206966781
glob = a/**/c*
glob = a/**/c**
blob = gs://my-bucket/a/b/c/abc-123.txt#1712257207431039
blob = gs://my-bucket/a/b/c/abc.txt#1712257207497081
blob = gs://my-bucket/a/z/c/azc-123.txt#1712257207116778
blob = gs://my-bucket/a/z/c/azc.txt#1712257206966781
```

### Notes
I believe the pattern `a/**/1.txt` most closely matches what you describe, and I do in fact receive back both objects I'd expect to `.../a/b/1.txt` and `.../a/z/1.txt`.

One behavioural note about object listing using `matchGlob`. Sometimes the results aren't contained in a single response from GCS, this is due to how some of the index of object and the matching is applied when paging. Double check you're using `Page#iterateAll()` or `Page#streamAll()` to ensure all pages are exhaustively evaluated.

**Comment by BenWhitehead** [comment]
Thank you for reporting back. I'm glad you were able get things working!
