### ISSUE TITLE
createFrom(BlobInfo blobInfo, Path path, int bufferSize, BlobWriteOption... options) ignores bufferSize

### ISSUE THREAD

**Issue by benjaminp** [googleapis/java-storage#2509]
The `Storage` API for creating an object from a local `Path` simply ignores its `bufferSize` parameter. This can be verified by looking at the implementation.

Maybe that's fine, and the `bufferSize` should just be documented as a hint.

**Comment by BenWhitehead** [comment]
Since https://github.com/googleapis/java-storage/commit/4c2f44e28a1ff19ffb2a02e3cefc062a1dd98fdc released in v2.25.0, when uploading the local file to GCS it is effectively piped directly out to the request and no longer needs to preallocate a buffer. The method signature was left with the parameter to keep binary compatibility.

**Comment by benjaminp** [comment]
That makes sense. But how about updating the documentation to describe `bufferSize` as vestigial?
