### ISSUE TITLE
allow specifying the content length for resumable uploads

### ISSUE THREAD

**Issue by benjaminp** [googleapis/java-storage#2511]
**Is your feature request related to a problem? Please describe.**
The resumable upload API allows [specifying a final length of the object](https://cloud.google.com/storage/docs/json_api/v1/parameters#xuploadcontentlength) if known in a HTTP header. There is no way to pass this value into the Java GCS API for resumable uploads, though.

**Describe the solution you'd like**
A `Storage.writer` method overload that takes the final content length.

**Comment by BenWhitehead** [comment]
In general we recommend folks use checksums for validation of all intended bytes reaching gcs rather than relying on the number of bytes. Using a checksum like crc32c will ensure the bytes are received in the correct sequence and match with what GCS receives.

For an example of how the crc32c precondition is provided to an upload, you can take a look at one of our integration tests that verify correct checksum plumbing and handling https://github.com/googleapis/java-storage/blob/50ac93b6b61806911737e389253739436dfb515c/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectChecksumSupportTest.java#L203-L204

To compute a crc32c checksum you can use Guava's crc32c HashFunction https://guava.dev/releases/33.1.0-jre/api/docs/com/google/common/hash/Hashing.html#crc32c()

**Comment by benjaminp** [comment]
I agree that a checksum of the content is preferable when available. However, sometimes you are proxying a file from a client that gives you the size upfront but not a checksum in which case GCS verifying the size is better than nothing.
