### ISSUE TITLE
If-Modified-Since and other request headers

### ISSUE THREAD

**Issue by oripwk** [googleapis/java-storage#628]
Hi,

The GCS API documents the capability of retrieving GCS object according to these standard headers [1]:
* `If-Match`
* `If-Modified-Since`
* `If-None-Match`
* `If-Unmodified-Since`

How can it be achieved using the Java client API's [get()](https://googleapis.dev/java/google-cloud-storage/latest/com/google/cloud/storage/Storage.html#get-com.google.cloud.storage.BlobId-com.google.cloud.storage.Storage.BlobGetOption...-) method?

Thanks

[1] https://cloud.google.com/storage/docs/xml-api/get-object-download#request_headers

**Comment by dmitry-fa** [comment]
@oripwk, thanks for that question.

For the time being the Java client doesn't support that. To achieve the similar effect it's recommended to use object versioning [[1]](https://cloud.google.com/storage/docs/object-versioning): `generation` / `metageneration` and avoid using  'etags' [[2]](https://cloud.google.com/storage/docs/object-versioning#avoid_etags).

The following code demonstrates how the existing client could be used to support `If-Match` / `If-None-Match`, where `generation` is used instead of `etag`.
```
    public static void main(String... args) throws Exception {
        Storage storage = StorageOptions.getDefaultInstance().getService();
        BlobId blobId = BlobId.of(bucketName, blobName);

        // create object
        BlobInfo blobInfo = BlobInfo.newBuilder(blobId).build();
        Blob blob = storage.create(blobInfo, new byte[10]);
        long generation = blob.getGeneration();
        System.out.println("Size: " + blob.getSize());

        // update object's content
        storage.create(blobInfo, new byte[15]);

        System.out.println("generationNotMatch size: " + storage.get(blobId, Storage.BlobGetOption.generationNotMatch(generation)).getSize());
        try {
            storage.get(blobId, Storage.BlobGetOption.generationMatch(generation));
        } catch (StorageException e) {
            System.out.println("generationMatch: " + e.getMessage());
        }
    }
```

To support `If-Modified-Since` / `If-Unmodified-Since` one can implement simple methods like:
```
    public static Blob getIfModifiedSince(Storage storage, BlobId blobId, long time) {
        Blob blob = storage.get(blobId);
        return blob != null && blob.getGeneration() > time ? blob : null;
    }
```
Please note, `storage.get(blobId)` will not cause content downloading, it will issue a single RPC to retrieve the current object properties.
`blob.getGeneration()` will not issue any RPC

Hope it helps, let us know if you have more questions.

Thanks,
Dmitry


[1] https://cloud.google.com/storage/docs/object-versioning
[2] https://cloud.google.com/storage/docs/object-versioning#avoid_etags
