### ISSUE TITLE
Cloud Storage: timeouts not being respected

### ISSUE THREAD

**Issue by pedro-carneiro** [googleapis/java-storage#699]
#### Environment details

1. OS type and version: Any
2. Java version: Any
3. Storage version: 1.104.0

#### Steps to reproduce

So, there's this application doing reads and writes in several objects of a Google Cloud Storage bucket. While the vast majority of these operations complete under 500ms, there are some that take from 10 to 40s. The disparity of values seemed to suggest the higher latencies were caused by retries. As such, stricter retry settings were configured.

But while setting a total timeout of 10 seconds, there were still some calls taking 20 seconds.

Looking at the source code, it seems the total timeout is only considered when a retry occurs. The first attempt doesn't seem to be limited in the time it takes. Specifically, [here](https://github.com/googleapis/gax-java/blob/90957ff78df968ae885aeaa4e41b2b738f4c2c25/gax/src/main/java/com/google/api/gax/retrying/DirectRetryingExecutor.java#L105): the `retryingFuture.getAttemptSettings()` object holds a value for `rpcTimeout` that doesn't seem to be considered anywhere.

#### Code example

The `Storage` object is created like this:

```kotlin
val retrySettings = RetrySettings.newBuilder()
  .setMaxAttempts(3)
  .setInitialRetryDelay(Duration.ofSeconds(1))
  .setMaxRetryDelay(Duration.ofSeconds(2))
  .setRetryDelayMultiplier(2.0)
  .setTotalTimeout(Duration.ofSeconds(10))
  .setInitialRpcTimeout(Duration.ofSeconds(10))
  .setRpcTimeoutMultiplier(1.0)
  .setMaxRpcTimeout(Duration.ofSeconds(10))
  .build()
return StorageOptions.newBuilder().setRetrySettings(retrySettings).build().service
```

#### Stack trace
```
com.google.cloud.storage.StorageException: Read timed out
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:229)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:776)
	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:60)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:53)
	at com.google.cloud.BaseWriteChannel.close(BaseWriteChannel.java:151)
	...
```

#### External references such as API reference guides

n/a

#### Any additional information below

Apologies if there's any improper configuration on my side, or if this is reported in the wrong project. Thank you 🙏

**Comment by frankyn** [comment]
Hi @pedro-carneiro,

Thank you for your patience on this issue. There might be a missing context to the underlying request to respect the provided timeouts. I'm investigating further, but just chiming in after a while.

**Comment by frankyn** [comment]
Here's additional info that I've been using to understand the timeout config:

Name | Definition | Default Value
-- | -- | --
Max Attempts | MaxAttempts defines the maximum number of attempts to perform. | 6
Initial Retry Delay | InitialRetryDelay controls the delay before the first retry. Subsequent retries will use this value adjusted according to the RetryDelayMultiplie | 1 second
Max Retry Delay | MaxRetryDelay puts a limit on the value of the retry delay, so that the RetryDelayMultiplier can't increase the retry delay higher than this amount | 32 seconds
Retry Delay Multiplier | RetryDelayMultiplier controls the change in retry delay. The retry delay of the previous call is multiplied by the RetryDelayMultiplier to calculate the retry delay for the next call. | 2
Total Timeout | TotalTimeout has ultimate control over how long the logic should keep trying the remote call until it gives up completely. The higher the total timeout, the more retries can be attempted. | 50 seconds
Initial RPC Timeout | InitialRpcTimeout controls the timeout for the initial RPC. Subsequent calls will use this value adjusted according to the RpcTimeoutMultiplier. | 50 seconds
RPC Timeout Multiplier | RpcTimeoutMultiplier controls the change in RPC timeout. The timeout of the previous call is multiplied by the RpcTimeoutMultiplier to calculate the timeout for the next call. | 1
Max RPC Timeout | MaxRpcTimeout puts a limit on the value of the RPC timeout, so that the RpcTimeoutMultiplier can't increase the RPC timeout higher than this amount. | 50 seconds

`rpcTimeout` is considered in the [ExponentialRetryAlgorithm](https://github.com/googleapis/gax-java/blob/49efdc38f2d6ca3838dcecee63dc6cd07f6c2b23/gax/src/main/java/com/google/api/gax/retrying/ExponentialRetryAlgorithm.java#L118-L167).

However, as you pointed out a request isn't interrupted until longer than 10 seconds. Repro provided at the end.


Hi @benwhitehead and @noahdietz, the Java gax library retry strategy is very complex one of you might have more context.

Do you know why configuring `totalTimeout` does not interrupt a request at the totalTimeout set and instead fails with `Read timed out` at a longer time?
I attempted reproing this with the [Storage Python emulator](https://github.com/frankyn/google-cloud-cpp/tree/add-retries/google/cloud/storage/emulator) sleeping for 20000 seconds on data transfer. 

The request eventually timeout but takes at least 20+ seconds when `totalTimeout` is set to 10 seconds.

To repro, I did the following:

1. Started the emulator in [branch](https://github.com/frankyn/google-cloud-cpp/tree/add-retries/google/cloud/storage/emulator) on port 9000

2. Add the following integration test:
```java
@Test
  public void testEmulator() throws IOException {
    String blobName = "test-empty-blob";
    RetrySettings retrySettings = RetrySettings.newBuilder()
            .setMaxAttempts(3)
            .setInitialRetryDelay(Duration.ofSeconds(1))
            .setMaxRetryDelay(Duration.ofSeconds(2))
            .setRetryDelayMultiplier(2.0)
            .setTotalTimeout(Duration.ofSeconds(10))
            .setInitialRpcTimeout(Duration.ofSeconds(1))
            .setRpcTimeoutMultiplier(1.0)
            .setMaxRpcTimeout(Duration.ofSeconds(10))
            .setJittered(false)
            .build();
    Storage storage = StorageOptions.newBuilder()
            .setHost("http://localhost:9000")
            .setRetrySettings(retrySettings)
            .build().getService();
    BlobInfo blobInfo = BlobInfo.newBuilder("bucket", blobName).build();
    int numberOfBytes = 0;
    try (WriteChannel writer = storage.writer(blobInfo)) {
      writer.setChunkSize(256*1024);
      byte[] content = BLOB_STRING_CONTENT.getBytes(UTF_8);
      for (int i = 0; i < 1024*1024; i++) {
        numberOfBytes += writer.write(ByteBuffer.wrap(content, 0, content.length));
      }
    }
  }
```
3. Watch it take longer than 10 seconds to fail and can't find why this is happening.

**Comment by noahdietz** [comment]
I'm only really familiar with the gRPC implementation of the gax-java mechanics but I am familiar with the retry/timeout logic as a whole. I know for gRPC, that the underlying implementation uses the gRPC RPC deadline mechanism. Essentially gax-java does some math to determine the RPC attempt timeout, then gives that to gRPC to calculate a deadline. So gax-java doesn't actually manage the timing and cancel calls, gRPC does. 

I don't know what the equivalent mechanism is for HTTP. @vam-google might be able to help us determine how it works.

I will follow up tomorrow 6/2 with more details/links, I'm traveling today and was just catching up.

**Comment by noahdietz** [comment]
Also, taking a step up in the stack, gax-java retry machinery will stop making attempts once the totalTimeout has been consumed/reached. Furthermore, RPC attempt timeouts will be truncated to the remainder in the totalTimeout if the "next" timeout is larger than the time remaining. But again, the in flight request cancellation/management is handled at the transport level and for gRPC it has its own mechanics for canceling the attempt in flight. 

I have a feeling it is not implemented for HTTP.

**Comment by frankyn** [comment]
Thanks @noahdietz! That helps point out that interruption of a request may not occur in the gax-java library - pending input from @vam-google and additional links when you're back tomorrow.

@pedro-carneiro I dug into into request timeouts given `TotalTimeout` does not interrupt requests based on the configured TotalTimeout and instead uses default timeout of [20 seconds](https://googleapis.dev/java/google-http-client/latest/com/google/api/client/http/HttpRequest.html#getReadTimeout--) which can be configured by doing the following snippet. @BenWhitehead we will need to reconcile the complexity for timeouts when updating retry strategy. 

```java
    TransportOptions transportOptions = HttpTransportOptions.newBuilder().setReadTimeout(1000).build();
    Storage storage = StorageOptions.newBuilder()
            .setRetrySettings(retrySettings)
            .setTransportOptions(transportOptions)
            .build().getService();
```

There 3 settings:

Timeout Name | Description | Default Value
--- | --- | ---
Connection Timeout | timeout in milliseconds to establish a connection or 0 for an infinite timeout | 20000 ms
Write Timeout | timeout in milliseconds to send POST/PUT data or 0 for an infinite timeout. | 0 - infinite timeout
Read Timeout | timeout in milliseconds to read data from an established connection or 0 for an infinite timeout | 20000 ms

**Comment by noahdietz** [comment]
Sharing this from @vam-google: 

Hi guys,

This is a sophisticated topic, and in general, the term "timeout" is heavily overloaded, to properly answer the question we need very rigorously define which of the many timeouts we are talking about. 

Without going into too much detail, it is worth mentioning, that `Storage` is a very different client from most of the other ones, it is a hand-written and HTTP1-based one, and even though it is integrated with gax-java, the integration is not as deep and fundamental as for the autogenerated gRPC-based ones. The `rpcTimeout` configs in `RetrySettings` are appreciated by the GAPIC gRPC clients, but for the manual http1-based clients, only as subset of properties from `RetrySettings` is actually used, and rpcTimeout is not one of them (i.e. it is basically ignored). There are many reasons why that happened, but basically everything comes to and attempt to make two very incompatible library sets (manual http1-based and generated gapic grpc-based) as similar to each other on the surface as possible. If you dive deep enough, the differences between the client types become more and more visible (like this one).

For GAPCI gRPC-based clients RetrySettigns determine both types of timing parameters - retries (i.e. when to an attempt), and each individual rpc timeouts (i.e. protocol-level thing). For manual clients like Storage, `RetrySettigns` determine only the retries part.  

As @frankyn pointed out, the proper way to configure individual rpc timeout is `HttpTransportOptions.setReadTimeout()` and `HttpTransportOptions.setConnectTimeout()`, those are not coming from gax-java and instead of configuring gRPC channel properties (this is what `RetrySettings` rpcTimeouts are about) would affect directly the timeout properties for `HttpRequest` from the `google-http-client`, which is the generic http client used by the manual client libraries.

I hope that helps.

**Comment by frankyn** [comment]
Thanks @noahdietz! I hope this helps address the gotcha for @pedro-carneiro. @BenWhitehead I think you'll want to scope this gotcha into the redesign work for retries. 

Closing issue as this question was addressed, and we are working on making this experience better for java-storage. We will include this feedback in redesign work we are doing.
